# Generated by Django 4.0.6 on 2022-07-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('decs', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
