# Generated by Django 4.0.6 on 2022-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('message', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
